### ISSUE TITLE
exceptions.AttributeError: instance has no attribute 'factory'

### ISSUE THREAD

**Issue by Kojoley** [fiorix/txredisapi#84]
After upgrading from 1.2 to 1.3 I constantly get errors across `self.factory`. I can't run txredisapi tests because of https://github.com/d11wtq/dockerpty/issues/7, but test cases are extremly simple.

```python
import txredisapi as redis
from twisted.internet import protocol
from twisted.internet import reactor


class RedisListenerProtocol(redis.SubscriberProtocol):
    pass

if __name__ == "__main__":
    host, port = "127.0.0.1", 6379
    protocol.ClientCreator(reactor, RedisListenerProtocol).connectTCP(host, port)
    reactor.run()
```

```
Unhandled error in Deferred:


Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 587, in doConnect
    self._connectDone()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 616, in _connectDone
    self.protocol.makeConnection(self)
  File "C:\Python27\lib\site-packages\twisted\internet\protocol.py", line 487, in makeConnection
    self.connectionMade()
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "C:\Python27\lib\site-packages\txredisapi.py", line 248, in connectionMade
    if self.factory.password is not None:
exceptions.AttributeError: RedisListenerProtocol instance has no attribute 'factory'
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 430, in _continueFiring
    callable(*args, **kwargs)
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 625, in disconnectAll
    failure.Failure(main.CONNECTION_LOST))
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 479, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 293, in connectionLost
    protocol.connectionLost(reason)
  File "C:\Python27\lib\site-packages\txredisapi.py", line 285, in connectionLost
    self.factory.delConnection(self)
exceptions.AttributeError: RedisListenerProtocol instance has no attribute 'factory'
```

```python
import txredisapi as redis
from twisted.internet import protocol
from twisted.internet import reactor


class RedisListenerProtocol(redis.SubscriberProtocol):
    def connectionMade(self):
        self.subscribe('channel_name')

if __name__ == "__main__":
    host, port = "127.0.0.1", 6379
    protocol.ClientCreator(reactor, RedisListenerProtocol).connectTCP(host, port)
    reactor.run()
```

```
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Python27\lib\site-packages\txredisapi.py", line 176, in dataReceived
    return self.rawDataReceived(data)
  File "C:\Python27\lib\site-packages\txredisapi.py", line 375, in rawDataReceived
    self.bulkDataReceived(bulk_buffer)
  File "C:\Python27\lib\site-packages\txredisapi.py", line 384, in bulkDataReceived
    el = self.tryConvertData(data)
  File "C:\Python27\lib\site-packages\txredisapi.py", line 395, in tryConvertData
    if self.factory.convertNumbers:
exceptions.AttributeError: RedisListenerProtocol instance has no attribute 'factory'

Unhandled Error
Traceback (most recent call last):
  File "C:\test2.py", line 13, in <module>
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1206, in mainLoop
    self.doIteration(t)
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 143, in doSelect
    _logrun(selectable, _drdw, selectable, method)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 154, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, method=="doRead")
  File "C:\Python27\lib\site-packages\twisted\internet\posixbase.py", line 260, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 479, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 293, in connectionLost
    protocol.connectionLost(reason)
  File "C:\Python27\lib\site-packages\txredisapi.py", line 285, in connectionLost
    self.factory.delConnection(self)
exceptions.AttributeError: RedisListenerProtocol instance has no attribute 'factory'
```
